
services:
  # Main Application API
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - go-project-network
    restart: unless-stopped
    volumes:
      - .:/app
    env_file:
      - .env
    # command: air -c .air.toml
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 5s
      timeout: 5s
      retries: 5

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: go-project-postgres-1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./create-postgres-databases.sh:/docker-entrypoint-initdb.d/10-create-postgres-databases.sh
    networks:
      - go-project-network
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5



networks:
  go-project-network:
    driver: bridge

volumes:
  postgres-data:
